Facilitator workflow
abetterinternet/prio-server pull request #108
Opened 2020-10-29 20:38 UTC by aaomidi

2020-10-29 22:10 UTC, tgeoghegan commented on .github/workflows/facilitator-test.yml
> +name: facilitator-test
We already have build, test and clippy in the `build-rust` job in `.github/worksflows/ci-build.yml`. I think the thing to do is add the new coverage target there.

2020-10-29 22:11 UTC, tgeoghegan requested changes
Please resolve this with the existing Rust checks in `.github/workflows/ci-build.yml`.

2020-10-29 22:12 UTC, aaomidi commented
Do you want me to make another job there or just integrate with `build-rust`? Because I need to use the nightly version of rust for this to work - are we fine changing the build to just use rust nightly?

2020-10-29 22:28 UTC, tgeoghegan commented
We should not use the nightly Rust toolchain for the regular CI build, because we want the build and test runs to reflect how we will build production binaries. Also it looks like using the nightly toolchain broke one of the steps in the existing job. I think making a separate job is the right thing, and please include a comment explaining why we need a separate toolchain.

2020-10-30 21:06 UTC, tgeoghegan commented
Looking good! Where do we actually get the coverage results though?

2020-10-30 21:26 UTC, aaomidi commented
The coverage results will be posted as a comment on the PR and available through the codecov website.https://codecov.io/gh/abetterinternet/prio-server/pull/108

2020-10-30 23:28 UTC, jsha approved these changes

2020-10-31 00:55 UTC, tgeoghegan approved these changes

2020-11-02 17:11 UTC, merged