Remove deploy-operator.
abetterinternet/prio-server pull request #1115
Opened 2021-11-11 04:13 UTC by BranLwyd

Our current plan is to use a cron job rather than an operator to do key-rotation work. While we may revisit the plan to use an operator in the future, for now it is dead code and it is causing at least a little confusion among other readers of this repo (https://github.com/abetterinternet/prio-server/issues/1112), so I'd like to remove it. We can retrieve if from Git history if it turns out to be necessary in the future.

2021-11-11 14:38 UTC, tgeoghegan approved these changes

2021-11-11 14:56 UTC, tgeoghegan requested changes
Besides deleting the code, we should delete the Terraform stuff that creates the CRD, or any other TF stuff that deploy-operator depended on.

2021-11-11 17:58 UTC, BranLwyd commented
OK, I think I got it all. (I didn't realize it was there, but locality_kubernetes serves as a useful example -- I'll be reintroducing per-locality kubernetes config soon since that's the intended "domain" of the cron job I'm setting up.)

2021-11-12 18:55 UTC, tgeoghegan approved these changes

2021-11-12 19:20 UTC, merged